### ISSUE TITLE
generalize to more downstream tasks

### ISSUE THREAD

**Issue by implus** [ShoufaChen/AdaptFormer#1]
Hi, thanks a lot for the wonderful work~! 
I notice that there is no fine-tuning result on ImageNet, neither downstream tasks like semantic segmentation/object detection. 
Have you tried several tasks as mentioned above?  Can the method possibly generalize to them?

Thanks again for your kind reply.

**Comment by ShoufaChen** [comment]
Hi, Thanks for your interest.

Since our model is pre-trained on the ImageNet, we didn't test the fine-tuning performance on ImageNet. We plan to fine-tune on ImageNet when we obtain a model pre-trained on a dataset larger than ImageNet.

For downstream dense prediction tasks, we are conducting related experiments. Thanks for your advice and please stay tuned.

**Comment by implus** [comment]
Thanks a lot!
